### ISSUE TITLE
A few ideas 🎉

### ISSUE THREAD

**Issue by jycouet** [Yedidyar/remult-cli#1]
Nice start! Thank's for sharing the repo.

A few open points/questions/comment
- [x] ~I would keep `DATABASE_URL` instead of `connectionString` to be as close as possible to remult.~
  - `connectionString` is good for arg, when  we will read from  .env, would be great to check `DATABASE_URL` => Like in remult
- [x] What if `tables` would be optional and if nothing is set it's all tables? (maybe having `include` & `exclude` to have more options?)
- [x] What if `dir` would be optional and if nothing is set it's going to a `shared` folder?
- [x] I don't know anything about `ink`, isn't it "too big"? (if it works it's works, just want to share that I had a few nodes "cli" with `@clack/prompts` and I like it a lot, light & fast)
- [ ] #10

**Comment by Yedidyar** [comment]
Thanks for the support 😄
I also thought about some of the improvements you suggested, you are more than welcome to contribute and open a pull request, just let me know what task you are taking so that there will be no conflicts.

**Comment by jycouet** [comment]
I don't exactly know where to start ^^
Maybe we could chat & align on discord? (I'm `jycouet` overthere too)

Speak to you soon

**Comment by jycouet** [comment]
Let's close this one. 
Thx a lot 🎉
