### ISSUE TITLE
uniqueOnBackend - The declaration was marked as deprecated

### ISSUE THREAD

**Issue by Easy-Cloud-in** [Yedidyar/remult-cli#97]
@Fields.string({ validate: [Validators.uniqueOnBackend] })
	categoryname!: string

The warning message   uniqueOnBackend depreciated  is this a problem? 
Do we have to change it to unique?

**Comment by yedidyar-ni** [comment]
Yes its a probably a problem.
Did you l look at the docs to the alternative?

**Comment by yedidyar-ni** [comment]
I appreciate your suggestion! Collaborative efforts are essential for improving code quality and functionality. If you come across any issues or have ideas for enhancements, feel free to contribute by submitting a pull request. Together, we can make the code even better! 😊👍

**Comment by Yedidyar** [comment]
You should change to unique insted
I open pr to resolve it on the cli side
